package com.legacyminecraft.poseidon.migration;

import org.junit.Assert;
import org.junit.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class LegacyNetServerHandlerWrapperThinnessTest {
    private static final Path NET_SERVER_HANDLER_PATH = Paths.get("src/main/java/net/minecraft/server/NetServerHandler.java");

    @Test
    public void netServerHandlerUsesCanonicalRoleAlignedDelegateNaming() throws IOException {
        String text = new String(Files.readAllBytes(NET_SERVER_HANDLER_PATH), StandardCharsets.UTF_8);

        Assert.assertTrue(text.contains("ConnectionHeartbeatExecutionSystem"));
        Assert.assertTrue(text.contains("connectionHeartbeatSystem"));
        Assert.assertTrue(text.contains("ConnectionHeartbeatThresholdPolicy"));
        Assert.assertTrue(text.contains("connectionHeartbeatThresholdPolicy"));
        Assert.assertTrue(text.contains("PlayerMoveInitializationPolicy"));
        Assert.assertTrue(text.contains("playerMoveInitializationPolicy"));
        Assert.assertTrue(text.contains("heartbeatActions"));
        Assert.assertTrue(text.contains("connectionHeartbeatExecutionSystem.applyHeartbeat("));
        Assert.assertTrue(text.contains("connectionLossExecutionSystem"));
        Assert.assertTrue(text.contains("connectionLossExecutionSystem.executeConnectionLoss("));
        Assert.assertTrue(text.contains("connectionTerminationSystem"));
        Assert.assertTrue(text.contains("incomingChatPacketHandler"));
        Assert.assertTrue(text.contains("incomingChatPacketExecutionSystem"));
        Assert.assertTrue(text.contains("incomingChatResultExecutionSystem"));
        Assert.assertTrue(text.contains("IncomingChatLimitPolicy"));
        Assert.assertTrue(text.contains("ChatAllowedCharacterPolicy"));
        Assert.assertTrue(text.contains("BlockInteractionDistancePolicy"));
        Assert.assertTrue(text.contains("PacketEventConfigPolicy"));
        Assert.assertTrue(text.contains("PlayerLeaveMessageConfigPolicy"));
        Assert.assertTrue(text.contains("incomingChatLimitPolicy"));
        Assert.assertTrue(text.contains("chatAllowedCharacterPolicy"));
        Assert.assertTrue(text.contains("blockInteractionDistancePolicy"));
        Assert.assertTrue(text.contains("packetEventConfigPolicy"));
        Assert.assertTrue(text.contains("playerLeaveMessageConfigPolicy"));
        Assert.assertTrue(text.contains("incomingChatActions"));
        Assert.assertTrue(text.contains("incomingChatPacketExecutionSystem.execute("));
        Assert.assertTrue(text.contains("entityActionPacketExecutionSystem"));
        Assert.assertTrue(text.contains("entityActionResultResolver"));
        Assert.assertTrue(text.contains("entityActionResultExecutionSystem"));
        Assert.assertTrue(text.contains("entityActionResultActions"));
        Assert.assertTrue(text.contains("entityActionPacketExecutionSystem.execute("));
        Assert.assertTrue(text.contains("packetSendExecutionSystem"));
        Assert.assertTrue(text.contains("packetSendResultResolver"));
        Assert.assertTrue(text.contains("packetSendResultExecutionSystem"));
        Assert.assertTrue(text.contains("packetSendActions"));
        Assert.assertTrue(text.contains("packetSendExecutionSystem.execute("));
        Assert.assertTrue(text.contains("playerInputPacketExecutionSystem"));
        Assert.assertTrue(text.contains("playerInputActions"));
        Assert.assertTrue(text.contains("playerInputPacketExecutionSystem.execute("));
        Assert.assertTrue(text.contains("unexpectedPacketProtocolErrorExecutionSystem"));
        Assert.assertTrue(text.contains("protocolErrorActions"));
        Assert.assertTrue(text.contains("unexpectedPacketProtocolErrorExecutionSystem.execute("));
        Assert.assertTrue(text.contains("hotbarSwitchPacketExecutionSystem"));
        Assert.assertTrue(text.contains("hotbarSwitchResolver"));
        Assert.assertTrue(text.contains("hotbarSwitchResultExecutionSystem"));
        Assert.assertTrue(text.contains("hotbarSwitchActions"));
        Assert.assertTrue(text.contains("hotbarSwitchPacketExecutionSystem.execute("));
        Assert.assertTrue(text.contains("respawnPacketExecutionSystem"));
        Assert.assertTrue(text.contains("respawnResultResolver"));
        Assert.assertTrue(text.contains("respawnResultExecutionSystem"));
        Assert.assertTrue(text.contains("respawnActions"));
        Assert.assertTrue(text.contains("respawnPacketExecutionSystem.execute("));
        Assert.assertTrue(text.contains("signUpdatePacketExecutionSystem"));
        Assert.assertTrue(text.contains("signUpdateActions"));
        Assert.assertTrue(text.contains("signUpdatePacketExecutionSystem.execute("));
        Assert.assertTrue(text.contains("incomingPacketEventSystem"));
        Assert.assertTrue(text.contains("movementBranchExecutionSystem"));
        Assert.assertTrue(text.contains("movementBranches"));
        Assert.assertTrue(text.contains("movementBranchExecutionSystem.execute("));
        Assert.assertTrue(text.contains("movementCheckReenableExecutionSystem"));
        Assert.assertTrue(text.contains("movementCheckReenableExecutionSystem.apply("));
        Assert.assertTrue(text.contains("packetSendPipelineSystem"));
        Assert.assertTrue(text.contains("playerGroundMovementSystem"));
        Assert.assertTrue(text.contains("playerMoveEventExecutionSystem"));
        Assert.assertTrue(text.contains("moveEventFlow"));
        Assert.assertTrue(text.contains("playerMoveEventExecutionSystem.execute("));
        Assert.assertTrue(text.contains("playerMoveOutcomeExecutionSystem"));
        Assert.assertTrue(text.contains("moveOutcomeActions"));
        Assert.assertTrue(text.contains("playerMoveOutcomeExecutionSystem.executeOutcome("));
        Assert.assertTrue(text.contains("playerTeleportRequestExecutionSystem"));
        Assert.assertTrue(text.contains("teleportDestinationResolver"));
        Assert.assertTrue(text.contains("teleportRequestActions"));
        Assert.assertTrue(text.contains("playerTeleportRequestExecutionSystem.execute("));
        Assert.assertTrue(text.contains("playerTeleportPlanApplySystem"));
        Assert.assertTrue(text.contains("teleportPlanActions"));
        Assert.assertTrue(text.contains("playerTeleportPlanApplySystem.applyPlan("));
        Assert.assertTrue(text.contains("playerMoveEventStateApplySystem"));
        Assert.assertTrue(text.contains("moveEventStateSink"));
        Assert.assertTrue(text.contains("playerMoveEventStateApplySystem.applyState("));
        Assert.assertTrue(text.contains("vehicleMoveOutcomeExecutionSystem"));
        Assert.assertTrue(text.contains("vehicleMoveActions"));
        Assert.assertTrue(text.contains("vehicleMoveOutcomeExecutionSystem.executeOutcome("));
        Assert.assertTrue(text.contains("groundMovementDecisionExecutionSystem"));
        Assert.assertTrue(text.contains("groundMovementDecisionExecutionSystem.executeDecision("));
        Assert.assertTrue(text.contains("groundMovementDecisionLogSystem"));
        Assert.assertTrue(text.contains("groundMovementConsoleLogBehaviour"));
        Assert.assertTrue(text.contains("groundMovementDecisionLogSystem.emitLogs("));
        Assert.assertTrue(text.contains("windowTransactionBehaviour"));
        Assert.assertTrue(text.contains("hotbarSelectionBehaviour"));
        Assert.assertTrue(text.contains("blockInteractionPacketHandler"));
        Assert.assertFalse(text.contains("connectionHeartbeatService"));
        Assert.assertFalse(text.contains("connectionTerminationService"));
        Assert.assertFalse(text.contains("incomingChatPacketService"));
        Assert.assertFalse(text.contains("packetSendPipelineService"));
        Assert.assertFalse(text.contains("windowTransactionService"));
        Assert.assertFalse(text.contains("hotbarSelectionService"));
        Assert.assertFalse(text.contains("import org.bukkit.craftbukkit.CraftServer;"));
        Assert.assertFalse(text.contains("import org.bukkit.craftbukkit.event.CraftEventFactory;"));
        Assert.assertTrue(text.contains("private final Server bukkitServer;"));
        Assert.assertFalse(text.contains("private final Server server;"));
        Assert.assertFalse(text.contains("if (this.disconnected) return;"));
        Assert.assertFalse(text.contains("movementPacketPolicy.shouldReEnableMovementCheck("));
        Assert.assertFalse(text.contains("new ConnectionLossExecutionSystem.ConnectionLossActions()"));
        Assert.assertFalse(text.contains("this.player.a(packet27.c(), packet27.e(), packet27.g(), packet27.h(), packet27.d(), packet27.f());"));
        Assert.assertFalse(text.contains("if (!result.isValid())"));
        Assert.assertFalse(text.contains("incomingChatPacketHandler.processIncomingChat("));
        Assert.assertFalse(text.contains("this.chat(result.getNormalizedMessage());"));
        Assert.assertFalse(text.contains("if (result == HotbarSelectionBehaviour.SwitchResult.INVALID_SELECTION)"));
        Assert.assertFalse(text.contains("this.disconnect(\"Invalid hotbar selection (Hacking?)\");"));
        Assert.assertFalse(text.contains("if (respawnResult.isRespawned())"));
        Assert.assertFalse(text.contains("this.player = respawnResult.getPlayer();"));
        Assert.assertFalse(text.contains("if (playerActionPacketHandler.handleEntityActionPacket(this.server, this.player, packet19entityaction))"));
        Assert.assertFalse(text.contains("if (packetSendPipelineSystem.sendPacket(this.networkManager, this.player, this.getPlayer(), packet, this.firePacketEvents))"));
        Assert.assertFalse(text.contains("this.disconnect(\"Protocol error, unexpected packet\");"));
        Assert.assertFalse(text.contains("Location to = playerTeleportCoordinator.resolveTeleportDestination("));
        Assert.assertFalse(text.contains("signUpdatePacketExecutionSystem.execute(this.player.dead, new SignUpdatePacketExecutionSystem.SignUpdateActions()"));
        Assert.assertFalse(text.contains("if (moveOutcomeDecision.shouldSendRollbackPacket())"));
        Assert.assertFalse(text.contains("if (moveOutcomeDecision.shouldTeleportPlayer())"));
        Assert.assertFalse(text.contains("if (moveOutcomeDecision.shouldReturn())"));
        Assert.assertFalse(text.contains("private void applyMovementEventState("));
        Assert.assertFalse(text.contains("if (vehicleMoveResult.isCrashAttempt())"));
        Assert.assertFalse(text.contains("if (vehicleMoveResult.isHandled())"));
        Assert.assertFalse(text.contains("groundMovementDecision.getAction() == PlayerGroundMovementSystem.GroundMovementDecision.Action.DISCONNECT"));
        Assert.assertFalse(text.contains("groundMovementDecision.getAction() == PlayerGroundMovementSystem.GroundMovementDecision.Action.TELEPORT_LAST_GOOD"));
        Assert.assertFalse(text.contains("groundMovementDecision.getAction() == PlayerGroundMovementSystem.GroundMovementDecision.Action.ABORT"));
        Assert.assertFalse(text.contains("private void logGroundMovementDecision("));
        Assert.assertFalse(text.contains("System.out.println(logLine);"));
        Assert.assertFalse(text.contains("\"settings.packet-events.enabled\""));
        Assert.assertFalse(text.contains("\"message.player.leave\""));
        Assert.assertFalse(text.contains("private static final int PLACE_DISTANCE_SQUARED = 6 * 6;"));
        Assert.assertFalse(text.contains("ConnectionHeartbeatSystem.HeartbeatDecision heartbeatDecision ="));
        Assert.assertFalse(text.contains("this.sendPacket(connectionHeartbeatSystem.createKeepAlivePacket());"));
        Assert.assertFalse(text.contains(",\n                20,\n"));
        Assert.assertFalse(text.contains("Double.MAX_VALUE"));
        Assert.assertFalse(text.contains("Float.MAX_VALUE"));
        Assert.assertFalse(text.contains("if (this.player.dead) return; // CraftBukkit"));
        Assert.assertFalse(text.contains("this.lastPosX = plan.getX();"));
        Assert.assertFalse(text.contains("this.player.setLocation(plan.getX(), plan.getY(), plan.getZ(), plan.getYaw(), plan.getPitch());"));
    }
}
