package com.legacyminecraft.poseidon.migration;

import org.junit.Assert;
import org.junit.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class LegacyCraftPlayerWrapperThinnessTest {
    private static final Path CRAFT_PLAYER_PATH =
            Paths.get("src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java");
    private static final Path PLAYER_IDENTITY_BRIDGE_BEHAVIOUR_PATH =
            Paths.get("src/main/java/com/legacyminecraft/poseidon/compat/bukkit/PlayerIdentityBridgeBehaviour.java");
    private static final Path PLAYER_VISIBILITY_BRIDGE_BEHAVIOUR_PATH =
            Paths.get("src/main/java/com/legacyminecraft/poseidon/compat/bukkit/PlayerVisibilityBridgeBehaviour.java");

    @Test
    public void craftPlayerDelegatesIdentityAndStatusPoliciesToCanonicalBehaviours() throws IOException {
        String text = new String(Files.readAllBytes(CRAFT_PLAYER_PATH), StandardCharsets.UTF_8);
        String playerIdentityBridgeText =
                new String(Files.readAllBytes(PLAYER_IDENTITY_BRIDGE_BEHAVIOUR_PATH), StandardCharsets.UTF_8);
        String playerVisibilityBridgeText =
                new String(Files.readAllBytes(PLAYER_VISIBILITY_BRIDGE_BEHAVIOUR_PATH), StandardCharsets.UTF_8);

        Assert.assertTrue(text.contains("PlayerOnlineStatusBridgeBehaviour"));
        Assert.assertTrue(text.contains("PlayerEyeHeightPolicy"));
        Assert.assertTrue(text.contains("PlayerIdentityBridgeBehaviour"));
        Assert.assertTrue(text.contains("PlayerProfileBridgeBehaviour"));
        Assert.assertTrue(text.contains("PlayerActionDispatchBehaviour"));
        Assert.assertTrue(text.contains("PlayerStatisticDispatchBehaviour"));
        Assert.assertTrue(text.contains("PlayerTeleportBridgeBehaviour"));
        Assert.assertTrue(text.contains("PlayerChunkChangePacketBehaviour"));
        Assert.assertTrue(text.contains("PlayerLocalEffectPacketBehaviour"));
        Assert.assertTrue(text.contains("PlayerStateBridgeBehaviour"));
        Assert.assertTrue(text.contains("PlayerContextBridgeBehaviour"));
        Assert.assertTrue(text.contains("PlayerServerContextBridgeBehaviour"));
        Assert.assertTrue(text.contains("PlayerConnectionContextBridgeBehaviour"));
        Assert.assertTrue(text.contains("PlayerOperatorStateBehaviour"));
        Assert.assertTrue(text.contains("EntityWrapperDescriptionBehaviour"));
        Assert.assertTrue(text.contains("EntityTypedHandleCastBehaviour"));
        Assert.assertTrue(text.contains("EntityHandleMutationBehaviour"));
        Assert.assertTrue(text.contains("PlayerModerationListBehaviour"));
        Assert.assertTrue(text.contains("PlayerVisibilityBridgeBehaviour"));
        Assert.assertTrue(text.contains("PlayerMessagingBridgeBehaviour"));
        Assert.assertTrue(text.contains("PLAYER_ONLINE_STATUS_BRIDGE_BEHAVIOUR.isOnline("));
        Assert.assertTrue(text.contains("PLAYER_SERVER_CONTEXT_BRIDGE_BEHAVIOUR.resolveOnlinePlayers(server)"));
        Assert.assertTrue(text.contains("PLAYER_ONLINE_STATUS_BRIDGE_BEHAVIOUR.resolveAddress("));
        Assert.assertTrue(text.contains("PLAYER_CONNECTION_CONTEXT_BRIDGE_BEHAVIOUR.resolveConnection(getHandle())"));
        Assert.assertTrue(text.contains("ENTITY_TYPED_HANDLE_CAST_BEHAVIOUR.castHandle(entity, EntityPlayer.class)"));
        Assert.assertTrue(text.contains("ENTITY_HANDLE_MUTATION_BEHAVIOUR.applyHandle(entity, new EntityHandleMutationBehaviour.HandleMutationCallbacks()"));
        Assert.assertTrue(text.contains("PLAYER_EYE_HEIGHT_POLICY.resolveEyeHeight(ignoreSneaking, isSneaking())"));
        Assert.assertTrue(text.contains("PLAYER_IDENTITY_BRIDGE_BEHAVIOUR.equalsByName(this, obj)"));
        Assert.assertTrue(text.contains("PLAYER_IDENTITY_BRIDGE_BEHAVIOUR.hashByName(getName())"));
        Assert.assertTrue(text.contains("ENTITY_WRAPPER_DESCRIPTION_BEHAVIOUR.craftPlayerToString(getName())"));
        Assert.assertTrue(text.contains("PLAYER_PROFILE_BRIDGE_BEHAVIOUR.getDisplayName(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_PROFILE_BRIDGE_BEHAVIOUR.setDisplayName(getHandle(), name)"));
        Assert.assertTrue(text.contains("PLAYER_PROFILE_BRIDGE_BEHAVIOUR.getUniqueId(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_PROFILE_BRIDGE_BEHAVIOUR.getCompassTarget(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_PROFILE_BRIDGE_BEHAVIOUR.getConnectionType(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_PROFILE_BRIDGE_BEHAVIOUR.getCanonicalConnectionType(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_PROFILE_BRIDGE_BEHAVIOUR.resetPlayerTime("));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.setCompassTarget(getHandle(), loc, PLAYER_MAP_PACKET_BEHAVIOUR)"));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.chat(getHandle(), msg)"));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.performCommand(server, this, command)"));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.playRawNote("));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.playEffect("));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.sendBlockChange("));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.sendChunkChange("));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.sendMap(getHandle(), map.getId(), renderData, PLAYER_MAP_PACKET_BEHAVIOUR)"));
        Assert.assertTrue(text.contains("PLAYER_STATISTIC_DISPATCH_BEHAVIOUR.validateSubStatisticRequest(statistic, material)"));
        Assert.assertTrue(text.contains("PLAYER_STATISTIC_DISPATCH_BEHAVIOUR.resolveStatisticId(statistic, material)"));
        Assert.assertTrue(text.contains("PLAYER_STATISTIC_DISPATCH_BEHAVIOUR.sendStatistic("));
        Assert.assertTrue(text.contains("PLAYER_TELEPORT_BRIDGE_BEHAVIOUR.teleport(server, this, getHandle(), location)"));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.sendChunkChange("));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.playRawNote("));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.setSneaking(getHandle(), sneak)"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.isPlayer()"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.isSneaking(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.loadData("));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.saveData("));
        Assert.assertTrue(text.contains("PLAYER_SERVER_CONTEXT_BRIDGE_BEHAVIOUR.resolveServerHandle(server)"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.updateInventory(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.setSleepingIgnored(getHandle(), isSleeping"));
        Assert.assertTrue(text.contains("PLAYER_CONTEXT_BRIDGE_BEHAVIOUR.resolveWorldHandle(getWorld())"));
        Assert.assertTrue(text.contains("PLAYER_CONTEXT_BRIDGE_BEHAVIOUR.renderMapData(map, this)"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.isSleepingIgnored(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.setPlayerTime(getHandle(), time, relative)"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.getPlayerTimeOffset(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.getPlayerTime(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.isPlayerTimeRelative(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.hasReceivedKeepAlive(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.isUsingReleaseToBeta(getHandle())"));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.playEffect("));
        Assert.assertTrue(text.contains("PLAYER_ACTION_DISPATCH_BEHAVIOUR.sendBlockChange("));
        Assert.assertTrue(text.contains("PLAYER_OPERATOR_STATE_BEHAVIOUR.isOperator("));
        Assert.assertTrue(text.contains("PLAYER_OPERATOR_STATE_BEHAVIOUR.updateOperatorState("));
        Assert.assertTrue(text.contains("PLAYER_OPERATOR_STATE_BEHAVIOUR.recalculatePermissionsIfChanged(perm, changed)"));
        Assert.assertTrue(text.contains("PLAYER_MODERATION_LIST_BEHAVIOUR.isBanned("));
        Assert.assertTrue(text.contains("PLAYER_MODERATION_LIST_BEHAVIOUR.setBanned("));
        Assert.assertTrue(text.contains("PLAYER_MODERATION_LIST_BEHAVIOUR.isWhitelisted("));
        Assert.assertTrue(text.contains("PLAYER_MODERATION_LIST_BEHAVIOUR.setWhitelisted("));
        Assert.assertTrue(text.contains("PLAYER_VISIBILITY_BRIDGE_BEHAVIOUR.hidePlayer(hiddenPlayers, this, player)"));
        Assert.assertTrue(text.contains("PLAYER_VISIBILITY_BRIDGE_BEHAVIOUR.showPlayer(hiddenPlayers, this, player)"));
        Assert.assertTrue(text.contains("PLAYER_VISIBILITY_BRIDGE_BEHAVIOUR.canSee(hiddenPlayers, player)"));
        Assert.assertTrue(text.contains("PLAYER_MESSAGING_BRIDGE_BEHAVIOUR.sendRawMessage("));
        Assert.assertTrue(text.contains("PLAYER_MESSAGING_BRIDGE_BEHAVIOUR.kickIfOnline("));
        Assert.assertTrue(text.contains("PLAYER_MESSAGING_BRIDGE_BEHAVIOUR.sendPacketIfOnline("));
        Assert.assertFalse(text.contains("EntityPlayer player = (EntityPlayer) obj;"));
        Assert.assertFalse(text.contains("SocketAddress addr = getHandle().netServerHandler.networkManager.getSocketAddress();"));
        Assert.assertFalse(text.contains("return getHandle().displayName;"));
        Assert.assertFalse(text.contains("getHandle().displayName = name;"));
        Assert.assertFalse(text.contains("return getHandle().playerUUID;"));
        Assert.assertFalse(text.contains("return getHandle().compassTarget;"));
        Assert.assertFalse(text.contains("PLAYER_ONLINE_STATUS_BRIDGE_BEHAVIOUR.resolveAddress(getHandle().netServerHandler)"));
        Assert.assertFalse(text.contains("return getHandle().netServerHandler.getConnectionType();"));
        Assert.assertFalse(text.contains("return getHandle().netServerHandler.getCanonicalConnectionType();"));
        Assert.assertFalse(text.contains("setPlayerTime(0, true);"));
        Assert.assertFalse(text.contains("getHandle().netServerHandler.chat(msg);"));
        Assert.assertFalse(text.contains("return server.dispatchCommand(this, command);"));
        Assert.assertFalse(text.contains("getHandle().netServerHandler.sendPacket(PLAYER_MAP_PACKET_BEHAVIOUR.createCompassPacket(loc));"));
        Assert.assertFalse(text.contains("if (isSneaking()) {"));
        Assert.assertFalse(text.contains("return true;"));
        Assert.assertFalse(text.contains("hash = 97 * hash + (this.getName() != null ? this.getName().hashCode() : 0);"));
        Assert.assertFalse(text.contains("while (amount > Byte.MAX_VALUE) {"));
        Assert.assertFalse(text.contains("sendStatistic(statistic.getId() + mat, amount);"));
        Assert.assertFalse(text.contains("int cx = x >> 4;"));
        Assert.assertFalse(text.contains("if (sx <= 0 || sy <= 0 || sz <= 0) {"));
        Assert.assertFalse(text.contains("PlayerTeleportEvent event = new PlayerTeleportEvent((Player) this, from, to);"));
        Assert.assertFalse(text.contains("entity.netServerHandler.teleport(to);"));
        Assert.assertFalse(text.contains("server.getHandle().moveToWorld(entity, toWorld.dimension, to);"));
        Assert.assertFalse(text.contains("Packet51MapChunk packet = new Packet51MapChunk(x, y, z, sx, sy, sz, data);"));
        Assert.assertFalse(text.contains("getHandle().setSneak(sneak);"));
        Assert.assertFalse(text.contains("server.getHandle().playerFileData.b(getHandle());"));
        Assert.assertFalse(text.contains("server.getHandle().playerFileData.a(getHandle());"));
        Assert.assertFalse(text.contains("getHandle().updateInventory(getHandle().activeContainer);"));
        Assert.assertFalse(text.contains("getHandle().fauxSleeping = isSleeping;"));
        Assert.assertFalse(text.contains("getHandle().timeOffset = time;"));
        Assert.assertFalse(text.contains("getHandle().relativeTime = relative;"));
        Assert.assertFalse(text.contains("return getHandle().netServerHandler.isReceivedKeepAlive();"));
        Assert.assertFalse(text.contains("return (EntityPlayer) entity;"));
        Assert.assertFalse(text.contains("super.setHandle((EntityHuman) entity);"));
        Assert.assertFalse(text.contains("List<Packet131> packets = PLAYER_MAP_PACKET_BEHAVIOUR.createMapPackets(map.getId(), renderData);"));
        Assert.assertFalse(text.contains("for (Packet131 packet : packets)"));
        Assert.assertFalse(text.contains("new Packet54PlayNoteBlock(loc.getBlockX(), loc.getBlockY(), loc.getBlockZ(), instrument, note)"));
        Assert.assertFalse(text.contains("Packet61 packet = new Packet61(packetData, loc.getBlockX(), loc.getBlockY(), loc.getBlockZ(), data);"));
        Assert.assertFalse(text.contains("Packet53BlockChange packet = new Packet53BlockChange(loc.getBlockX(), loc.getBlockY(), loc.getBlockZ(), ((CraftWorld) loc.getWorld()).getHandle());"));
        Assert.assertFalse(text.contains("((CraftMapView) map).render(this)"));
        Assert.assertFalse(text.contains("((CraftWorld) getWorld()).getHandle()"));
        Assert.assertFalse(text.contains("if (value == isOp()) return;"));
        Assert.assertFalse(text.contains("if (!changed) {"));
        Assert.assertFalse(text.contains("PLAYER_ONLINE_STATUS_BRIDGE_BEHAVIOUR.isOnline(server.getHandle().players, getName())"));
        Assert.assertFalse(text.contains("PLAYER_OPERATOR_STATE_BEHAVIOUR.isOperator(server.getHandle(), getName())"));
        Assert.assertFalse(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.loadData(server.getHandle(), getHandle())"));
        Assert.assertFalse(text.contains("PLAYER_STATE_BRIDGE_BEHAVIOUR.saveData(server.getHandle(), getHandle())"));
        Assert.assertFalse(text.contains("PLAYER_MODERATION_LIST_BEHAVIOUR.isBanned(server.getHandle(), getName())"));
        Assert.assertFalse(text.contains("PLAYER_MODERATION_LIST_BEHAVIOUR.setBanned(server.getHandle(), getName(), value)"));
        Assert.assertFalse(text.contains("PLAYER_MODERATION_LIST_BEHAVIOUR.isWhitelisted(server.getHandle(), getName())"));
        Assert.assertFalse(text.contains("PLAYER_MODERATION_LIST_BEHAVIOUR.setWhitelisted(server.getHandle(), getName(), value)"));
        Assert.assertFalse(text.contains("server.getHandle().banByName.contains(getName().toLowerCase())"));
        Assert.assertFalse(text.contains("server.getHandle().a(getName().toLowerCase());"));
        Assert.assertFalse(text.contains("hiddenPlayers.add(player.getUniqueId());"));
        Assert.assertFalse(text.contains("EntityTracker tracker = ((WorldServer) entity.world).tracker;"));
        Assert.assertFalse(text.contains("getHandle().netServerHandler.sendPacket(new Packet3Chat(message));"));
        Assert.assertFalse(text.contains("PLAYER_MESSAGING_BRIDGE_BEHAVIOUR.sendRawMessage(getHandle().netServerHandler, message, getName())"));
        Assert.assertFalse(text.contains("PLAYER_MESSAGING_BRIDGE_BEHAVIOUR.kickIfOnline(isOnline(), getHandle().netServerHandler, message)"));
        Assert.assertFalse(text.contains("PLAYER_MESSAGING_BRIDGE_BEHAVIOUR.sendPacketIfOnline(player, getHandle().netServerHandler, packet)"));
        Assert.assertFalse(text.contains("PLAYER_STATISTIC_DISPATCH_BEHAVIOUR.sendStatistic(getHandle().netServerHandler, id, amount)"));
        Assert.assertFalse(text.contains("if (this.isOnline() && !getHandle().netServerHandler.disconnected)"));
        Assert.assertFalse(text.contains("NetServerHandler nsh = getHandle().netServerHandler;"));
        Assert.assertFalse(text.contains("return \"CraftPlayer{\" + \"name=\" + getName() + '}';"));
        Assert.assertTrue(playerIdentityBridgeText.contains("PlayerWrapperProjectionBridgeBehaviour"));
        Assert.assertTrue(playerIdentityBridgeText.contains("PLAYER_WRAPPER_PROJECTION_BRIDGE_BEHAVIOUR"));
        Assert.assertTrue(playerIdentityBridgeText.contains("requireCraftPlayer((org.bukkit.entity.Player) otherObject)"));
        Assert.assertFalse(playerIdentityBridgeText.contains("CraftPlayer other = (CraftPlayer) otherObject;"));
        Assert.assertTrue(playerVisibilityBridgeText.contains("WorldServerProjectionBridgeBehaviour"));
        Assert.assertTrue(playerVisibilityBridgeText.contains("WORLD_SERVER_PROJECTION_BRIDGE_BEHAVIOUR.resolveEntityTracker(observerHandle.world)"));
        Assert.assertFalse(playerVisibilityBridgeText.contains("EntityTracker tracker = ((WorldServer) observerHandle.world).tracker;"));
    }
}
