package com.legacyminecraft.poseidon.migration;

import org.junit.Assert;
import org.junit.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class LegacyWorldWrapperThinnessTest {
    private static final Path WORLD_PATH = Paths.get("src/main/java/net/minecraft/server/World.java");

    @Test
    public void worldDelegatesSpawnAndTopBlockPoliciesToCanonicalBehaviour() throws IOException {
        String text = new String(Files.readAllBytes(WORLD_PATH), StandardCharsets.UTF_8);

        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldBlockQueryBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldBlockMutationBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldBlockStateMutationBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldBlockPhysicsExecutionBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldBlockUpdateBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.compat.bukkit.WorldBlockPhysicsEventBridgeBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.compat.bukkit.WorldEntitySpawnEventBridgeBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldAccessNotificationBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldChunkAccessCacheBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldChunkLoadWindowBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldLightUpdateBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldLightQueryBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldLightWriteBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldEntityAdditionBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldEntityRemovalBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldEntityChunkDetachBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldPhysicsNeighbourBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldSavePipelineBehaviour;"));
        Assert.assertTrue(text.contains("import com.legacyminecraft.poseidon.world.WorldSpawnPlacementBehaviour;"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_QUERY_BEHAVIOUR.getTypeId(this, i, j, k)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_QUERY_BEHAVIOUR.isEmpty(this, i, j, k)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_QUERY_BEHAVIOUR.getMaterial(this, i, j, k)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_QUERY_BEHAVIOUR.getData(this, i, j, k)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_QUERY_BEHAVIOUR.isChunkCellLoaded(this, i, j, k)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_QUERY_BEHAVIOUR.getLightLevelClamped(this, i, j, k, 0)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_QUERY_BEHAVIOUR.hasDirectSkyAccess(this, i, j, k)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_QUERY_BEHAVIOUR.getHighestBlockYAt(this, i, j)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_QUERY_BEHAVIOUR.usesNeighborBrightness(l)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_QUERY_BEHAVIOUR.maxNeighborBrightness(i1, j1, k1, l1, i2)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_QUERY_BEHAVIOUR.getLightLevel(this, i, j, k, 15, this.f)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_MUTATION_BEHAVIOUR.setRawTypeIdAndData(this, i, j, k, l, i1)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_MUTATION_BEHAVIOUR.setRawTypeId(this, i, j, k, l)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_MUTATION_BEHAVIOUR.setRawData(this, i, j, k, l)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_STATE_MUTATION_BEHAVIOUR.applyRawData(this, i, j, k, l)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_STATE_MUTATION_BEHAVIOUR.applyRawTypeId(this, i, j, k, l)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_STATE_MUTATION_BEHAVIOUR.applyRawTypeIdAndData(this, i, j, k, l, i1)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_STATE_MUTATION_BEHAVIOUR.resolveUpdateTypeId(old, l)"));
        Assert.assertTrue(text.contains("mutationResult.shouldNotifyUpdate"));
        Assert.assertTrue(text.contains("mutationResult.typeId"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_PHYSICS_EXECUTION_BEHAVIOUR.applyNeighbourPhysics("));
        Assert.assertTrue(text.contains("WORLD_BLOCK_UPDATE_BEHAVIOUR.notifyAndApplyPhysics(this, i, j, k, l)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_UPDATE_BEHAVIOUR.normalizeVerticalRange(k, l)"));
        Assert.assertTrue(text.contains("WORLD_BLOCK_PHYSICS_EVENT_BRIDGE_BEHAVIOUR"));
        Assert.assertTrue(text.contains("WORLD_PHYSICS_NEIGHBOUR_BEHAVIOUR.cardinalNeighbors(i, j, k)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifyBlockChanged(this.u, i, j, k)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifySingleBlockRange(this.u, i, j, k)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifyBlockRange(this.u, i, j, k, l, i1, j1)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifySound(this.u, s, entity.locX, entity.locY - (double) entity.height, entity.locZ, f, f1)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifySound(this.u, s, d0, d1, d2, f, f1)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifyLevelEvent(this.u, s, i, j, k)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifyParticle(this.u, s, d0, d1, d2, d3, d4, d5)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifyEntityAdded(this.u, entity)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifyEntityRemoved(this.u, entity)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifyLightLevelChanged(this.u)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifyTileEntityChanged(this.u, i, j, k, tileentity)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.notifyAuxEffect(this.u, entityhuman, i, j, k, l, i1)"));
        Assert.assertTrue(text.contains("WORLD_ACCESS_NOTIFICATION_BEHAVIOUR.addWorldAccessListener(this.u, iworldaccess)"));
        Assert.assertTrue(text.contains("WORLD_CHUNK_ACCESS_CACHE_BEHAVIOUR.getChunkAtWorldCoords(this, i, j)"));
        Assert.assertTrue(text.contains("WORLD_CHUNK_ACCESS_CACHE_BEHAVIOUR.resolveCachedChunk("));
        Assert.assertTrue(text.contains("WORLD_SPAWN_PLACEMENT_BEHAVIOUR.canSpawn(this.getWorld(), this.worldProvider, this.generator, x, z)"));
        Assert.assertTrue(text.contains("WORLD_SPAWN_PLACEMENT_BEHAVIOUR.findTopSolidBlockType(this, i, j, 63)"));
        Assert.assertTrue(text.contains("WORLD_SPAWN_PLACEMENT_BEHAVIOUR.nextSpawnCoordinate(i, this.random)"));
        Assert.assertTrue(text.contains("WORLD_SPAWN_PLACEMENT_BEHAVIOUR.nextSpawnCoordinate(j, this.random)"));
        Assert.assertTrue(text.contains("WORLD_SPAWN_PLACEMENT_BEHAVIOUR.shouldFallbackToOrigin(attempts, 1024)"));
        Assert.assertTrue(text.contains("WORLD_CHUNK_LOAD_WINDOW_BEHAVIOUR.isBlockLoaded(this.chunkProvider, i, j, k)"));
        Assert.assertTrue(text.contains("WORLD_CHUNK_LOAD_WINDOW_BEHAVIOUR.isChunkLoaded(this.chunkProvider, i, j)"));
        Assert.assertTrue(text.contains("WORLD_CHUNK_LOAD_WINDOW_BEHAVIOUR.areChunksLoadedAround(this.chunkProvider, i, j, k, l)"));
        Assert.assertTrue(text.contains("WORLD_CHUNK_LOAD_WINDOW_BEHAVIOUR.areChunksLoaded(this.chunkProvider, i, j, k, l, i1, j1)"));
        Assert.assertTrue(text.contains("WORLD_LIGHT_UPDATE_BEHAVIOUR.shouldProcessUpdate(this.worldProvider.e, enumskyblock)"));
        Assert.assertTrue(text.contains("WORLD_LIGHT_UPDATE_BEHAVIOUR.resolveTargetLightValue(this, enumskyblock, i, j, k, l)"));
        Assert.assertTrue(text.contains("WORLD_LIGHT_UPDATE_BEHAVIOUR.shouldPropagateUpdate(this.a(enumskyblock, i, j, k), targetLightValue)"));
        Assert.assertTrue(text.contains("WORLD_LIGHT_QUERY_BEHAVIOUR.queryLightValue(this, enumskyblock, i, j, k, enumskyblock.c)"));
        Assert.assertTrue(text.contains("WORLD_LIGHT_QUERY_BEHAVIOUR.mapBrightness(this.worldProvider.f, this.getLightLevel(i, j, k))"));
        Assert.assertTrue(text.contains("WORLD_LIGHT_WRITE_BEHAVIOUR.writeLightValue(this, this.u, enumskyblock, i, j, k, l)"));
        Assert.assertTrue(text.contains("WORLD_ENTITY_ADDITION_BEHAVIOUR.entityChunkCoordinate(entity.locX)"));
        Assert.assertTrue(text.contains("WORLD_ENTITY_ADDITION_BEHAVIOUR.entityChunkCoordinate(entity.locZ)"));
        Assert.assertTrue(text.contains("WORLD_ENTITY_SPAWN_EVENT_BRIDGE_BEHAVIOUR.shouldCancelSpawn(entity, spawnReason)"));
        Assert.assertTrue(text.contains("WORLD_ENTITY_ADDITION_BEHAVIOUR.shouldRejectBecauseChunkNotLoaded(flag, this.isChunkLoaded(i, j))"));
        Assert.assertTrue(text.contains("WORLD_ENTITY_ADDITION_BEHAVIOUR.addEntityToChunkAndList(this, this.entityList, entity, i, j)"));
        Assert.assertTrue(text.contains("WORLD_ENTITY_REMOVAL_BEHAVIOUR.isPlayer(entity)"));
        Assert.assertTrue(text.contains("WORLD_ENTITY_REMOVAL_BEHAVIOUR.addPlayer(this.players, entity)"));
        Assert.assertTrue(text.contains("WORLD_ENTITY_REMOVAL_BEHAVIOUR.detachMounts(entity)"));
        Assert.assertTrue(text.contains("WORLD_ENTITY_REMOVAL_BEHAVIOUR.markDeadAndWasPlayer(entity)"));
        Assert.assertTrue(text.contains("WORLD_ENTITY_REMOVAL_BEHAVIOUR.removePlayer(this.players, entity)"));
        Assert.assertTrue(text.contains("WORLD_ENTITY_CHUNK_DETACH_BEHAVIOUR.detachFromChunkIfPresent(this, entity, i, j)"));
        Assert.assertTrue(text.contains("WORLD_SAVE_PIPELINE_BEHAVIOUR.canSave(this.chunkProvider)"));
        Assert.assertTrue(text.contains("WORLD_SAVE_PIPELINE_BEHAVIOUR.notifySavingLevel(iprogressupdate)"));
        Assert.assertTrue(text.contains("WORLD_SAVE_PIPELINE_BEHAVIOUR.notifySavingChunks(iprogressupdate)"));
        Assert.assertTrue(text.contains("WORLD_SAVE_PIPELINE_BEHAVIOUR.saveChunks(this.chunkProvider, flag, iprogressupdate)"));
        Assert.assertTrue(text.contains("WORLD_SAVE_PIPELINE_BEHAVIOUR.persistWorldState(this, this.w, this.worldData, this.players, this.worldMaps)"));
        Assert.assertFalse(text.contains("return this.generator.canSpawn(this.getWorld(), x, z);"));
        Assert.assertFalse(text.contains("return i >= -32000000 && k >= -32000000 && i < 32000000 && k <= 32000000 ? (j < 0 ? 0 : (j >= 128 ? 0 : this.getChunkAt(i >> 4, k >> 4).getTypeId(i & 15, j, k & 15))) : 0;"));
        Assert.assertFalse(text.contains("return this.getTypeId(i, j, k) == 0;"));
        Assert.assertFalse(text.contains("return l == 0 ? Material.AIR : Block.byId[l].material;"));
        Assert.assertFalse(text.contains("return chunk.getData(i, j, k);"));
        Assert.assertFalse(text.contains("return this.getChunkAt(i >> 4, k >> 4).c(i & 15, j, k & 15, 0);"));
        Assert.assertFalse(text.contains("if (l == Block.STEP.id || l == Block.SOIL.id || l == Block.COBBLESTONE_STAIRS.id || l == Block.WOOD_STAIRS.id)"));
        Assert.assertFalse(text.contains("this.notify(i, j, k);"));
        Assert.assertFalse(text.contains("this.applyPhysics(i, j, k, l);"));
        Assert.assertFalse(text.contains("this.k(i - 1, j, k, l);"));
        Assert.assertFalse(text.contains("this.k(i + 1, j, k, l);"));
        Assert.assertFalse(text.contains("this.k(i, j - 1, k, l);"));
        Assert.assertFalse(text.contains("this.k(i, j + 1, k, l);"));
        Assert.assertFalse(text.contains("this.k(i, j, k - 1, l);"));
        Assert.assertFalse(text.contains("this.k(i, j, k + 1, l);"));
        Assert.assertFalse(text.contains("CraftWorld world = ((WorldServer) this).getWorld();"));
        Assert.assertFalse(text.contains("BlockPhysicsEvent event = new BlockPhysicsEvent(world.getBlockAt(i, j, k), l);"));
        Assert.assertFalse(text.contains("if (k > l) {"));
        Assert.assertFalse(text.contains("if (j1 > i1)"));
        Assert.assertFalse(text.contains("if (k1 > i1)"));
        Assert.assertFalse(text.contains("if (l1 > i1)"));
        Assert.assertFalse(text.contains("if (i2 > i1)"));
        Assert.assertFalse(text.contains("return chunk.c(i, j, k, this.f);"));
        Assert.assertFalse(text.contains("if (this.setRawData(i, j, k, l)) {"));
        Assert.assertFalse(text.contains("this.update(i, j, k, l == 0 ? old : l);"));
        Assert.assertFalse(text.contains("} else if (j >= 128) {"));
        Assert.assertFalse(text.contains("return chunk.c(i, j, k);"));
        Assert.assertFalse(text.contains("return this.getChunkAt(i >> 4, k >> 4).c(i & 15, j, k & 15);"));
        Assert.assertFalse(text.contains("return chunk.b(i & 15, j & 15);"));
        Assert.assertFalse(text.contains("return chunk.a(i & 15, j, k & 15, l, i1);"));
        Assert.assertFalse(text.contains("return chunk.a(i & 15, j, k & 15, l);"));
        Assert.assertFalse(text.contains("chunk.b(i, j, k, l);"));
        Assert.assertFalse(text.contains("for (k = 63; !this.isEmpty(i, k + 1, j); ++k)"));
        Assert.assertFalse(text.contains("if (attempts > 1024)"));
        Assert.assertFalse(text.contains("return j >= 0 && j < 128 ? this.isChunkLoaded(i >> 4, k >> 4) : false;"));
        Assert.assertFalse(text.contains("return this.chunkProvider.isChunkLoaded(i, j);"));
        Assert.assertFalse(text.contains("return this.a(i - l, j - l, k - l, i + l, j + l, k + l);"));
        Assert.assertFalse(text.contains("if (i1 >= 0 && j < 128)"));
        Assert.assertFalse(text.contains("return this.getChunkAt(i >> 4, j >> 4);"));
        Assert.assertFalse(text.contains("return this.worldProvider.f[this.getLightLevel(i, j, k)];"));
        Assert.assertFalse(text.contains("if (entity.passenger != null)"));
        Assert.assertFalse(text.contains("entity.die();"));
        Assert.assertFalse(text.contains("if (entity instanceof EntityHuman) {\n            flag = true;\n        }"));
        Assert.assertFalse(text.contains("this.players.add(entityhuman);"));
        Assert.assertFalse(text.contains("this.players.remove((EntityHuman) entity);"));
        Assert.assertFalse(text.contains("CreatureSpawnEvent event = CraftEventFactory.callCreatureSpawnEvent((EntityLiving) entity, spawnReason);"));
        Assert.assertFalse(text.contains("ItemSpawnEvent event = CraftEventFactory.callItemSpawnEvent((EntityItem) entity);"));
        Assert.assertFalse(text.contains("if (!flag && !this.isChunkLoaded(i, j))"));
        Assert.assertFalse(text.contains("this.getChunkAt(i, j).a(entity);"));
        Assert.assertFalse(text.contains("if (entity.bG && this.isChunkLoaded(i, j)) {"));
        Assert.assertFalse(text.contains("this.getChunkAt(i, j).b(entity);"));
        Assert.assertFalse(text.contains("((IWorldAccess) this.u.get(i)).a(s, entity.locX, entity.locY - (double) entity.height, entity.locZ, f, f1);"));
        Assert.assertFalse(text.contains("((IWorldAccess) this.u.get(i)).a(s, d0, d1, d2, f, f1);"));
        Assert.assertFalse(text.contains("((IWorldAccess) this.u.get(l)).a(s, i, j, k);"));
        Assert.assertFalse(text.contains("((IWorldAccess) this.u.get(i)).a(s, d0, d1, d2, d3, d4, d5);"));
        Assert.assertFalse(text.contains("((IWorldAccess) this.u.get(i)).a(entity);"));
        Assert.assertFalse(text.contains("((IWorldAccess) this.u.get(i)).b(entity);"));
        Assert.assertFalse(text.contains("((IWorldAccess) this.u.get(k)).a();"));
        Assert.assertFalse(text.contains("((IWorldAccess) this.u.get(l)).a(i, j, k, tileentity);"));
        Assert.assertFalse(text.contains("((IWorldAccess) this.u.get(j1)).a(entityhuman, i, j, k, l, i1);"));
        Assert.assertFalse(text.contains("this.u.add(iworldaccess);"));
        Assert.assertFalse(text.contains("this.lastChunkAccessed = this.chunkProvider.getOrCreateChunk(i, j);"));
        Assert.assertFalse(text.contains("this.chunkProvider.saveChunks(flag, iprogressupdate);"));
        Assert.assertFalse(text.contains("this.w.a(this.worldData, this.players);"));
    }
}
